//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailChecker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Posteingang")]
        public string inboxName_DE {
            get {
                return ((string)(this["inboxName_DE"]));
            }
            set {
                this["inboxName_DE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Inbox")]
        public string inboxName_EN {
            get {
                return ((string)(this["inboxName_EN"]));
            }
            set {
                this["inboxName_EN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6f81a959248444388738f0ef0e4b5b35")]
        public string ContentModerator_SubscriptionKey {
            get {
                return ((string)(this["ContentModerator_SubscriptionKey"]));
            }
            set {
                this["ContentModerator_SubscriptionKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ocp-Apim-Subscription-Key")]
        public string OcpApimSubscriptionKey {
            get {
                return ((string)(this["OcpApimSubscriptionKey"]));
            }
            set {
                this["OcpApimSubscriptionKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://westus.api.cognitive.microsoft.com/contentmoderator/moderate/v1.0/Process" +
            "Text/DetectLanguage?")]
        public string CognitiveServicesUri_ContentModerator_DetectLanguage {
            get {
                return ((string)(this["CognitiveServicesUri_ContentModerator_DetectLanguage"]));
            }
            set {
                this["CognitiveServicesUri_ContentModerator_DetectLanguage"] = value;
            }
        }
    }
}
